In [1]:
import tensorflow as tf

In [2]:
#initialization of tensors

In [7]:
x = tf.constant(4)
print(x)

tf.Tensor(4, shape=(), dtype=int32)


In [8]:
x = tf.constant(4,shape=(1,1))
print(x)

tf.Tensor([[4]], shape=(1, 1), dtype=int32)


In [9]:
x = tf.constant(4,shape=(1,1),dtype = tf.float32)
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [10]:
x = tf.constant([[1,2,3],[4,5,6]])
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [11]:
x = tf.ones((3,3))
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [12]:
x = tf.zeros((3,3))
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [13]:
x = tf.eye(3)  #Identity matrix
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [14]:
x = tf.random.normal((3,3),mean=0,stddev=1)
print(x)

tf.Tensor(
[[-0.5237944   0.39326605  0.6889893 ]
 [ 0.2956016   2.7104726   0.04060665]
 [ 1.0620819  -0.19712195  1.2238592 ]], shape=(3, 3), dtype=float32)


In [16]:
x = tf.random.uniform((1,3),minval=0,maxval=1)
x

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.94957924, 0.6417607 , 0.1575849 ]], dtype=float32)>

In [18]:
x = tf.range(9)
x

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8])>

In [20]:
x = tf.range(start=1,limit=10,delta=2)
x

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9])>

In [22]:
x = tf.cast(x,dtype=tf.float32)
x

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([1., 3., 5., 7., 9.], dtype=float32)>

In [23]:
x = tf.constant([1,2,3])
y = tf.constant([9,8,7])
z = tf.add(x,y)
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 10, 10])>

In [25]:
z = x+y
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 10, 10])>

In [26]:
z = tf.subtract(x,y)
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-8, -6, -4])>

In [28]:
z = x-y
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-8, -6, -4])>

In [34]:
z = tf.multiply(x,y)
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 9, 16, 21])>

In [35]:
z = x*y
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 9, 16, 21])>

In [30]:
z = tf.divide(x,y)
z

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.11111111, 0.25      , 0.42857143])>

In [33]:
z = x/y 
z

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.11111111, 0.25      , 0.42857143])>

In [37]:
z = tf.tensordot(x,y,axes=1)
z

<tf.Tensor: shape=(), dtype=int32, numpy=46>

In [39]:
z = tf.reduce_sum(x*y,axis=0)
z

<tf.Tensor: shape=(), dtype=int32, numpy=46>

In [40]:
z = x**5
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([  1,  32, 243])>

In [42]:
x = tf.random.normal((2,3))
y = tf.random.normal((3,4))

In [43]:
x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 0.99826676,  0.02922763, -2.0814426 ],
       [ 0.17047492,  0.75229067,  0.04064756]], dtype=float32)>

In [44]:
y

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 1.4507198 , -0.79685575,  0.10739002,  1.8798419 ],
       [ 0.0651649 ,  0.22313291, -0.08651398,  0.11878919],
       [-0.2485181 , -0.78966826, -0.03092525,  0.8157375 ]],
      dtype=float32)>

In [45]:
z = tf.matmul(x,y)
z

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[ 1.9673861e+00,  8.5469621e-01,  1.6904444e-01,  1.8214491e-01],
       [ 2.8623265e-01, -8.1201848e-05, -4.8033390e-02,  4.4298762e-01]],
      dtype=float32)>

In [46]:
z = x@y
z

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[ 1.9673861e+00,  8.5469621e-01,  1.6904444e-01,  1.8214491e-01],
       [ 2.8623265e-01, -8.1201848e-05, -4.8033390e-02,  4.4298762e-01]],
      dtype=float32)>

In [ ]:
#Indexing

In [47]:
x = tf.constant([0,1,1,2,3,1,2,3])
x

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([0, 1, 1, 2, 3, 1, 2, 3])>

In [48]:
print(x[:])

tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)


In [49]:
print(x[1:])

tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)


In [50]:
print(x[1:3])

tf.Tensor([1 1], shape=(2,), dtype=int32)


In [51]:
print(x[::2])

tf.Tensor([0 1 3 2], shape=(4,), dtype=int32)


In [53]:
print(x[::-1])

tf.Tensor([3 2 1 3 2 1 1 0], shape=(8,), dtype=int32)


In [54]:
indices = tf.constant([0,3])
x_ind = tf.gather(x,indices)
x_ind

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([0, 2])>

In [55]:
x = tf.constant([[1,2],[3,4],[5,6]])
x

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

In [56]:
print(x[0,:])

tf.Tensor([1 2], shape=(2,), dtype=int32)


In [57]:
print(x[0:2,:])

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [58]:
#Reshaping

In [59]:
x = tf.range(9)
x

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8])>

In [60]:
x = tf.reshape(x,(3,3))
x

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])>

In [61]:
x = tf.transpose(x,perm=[1,0])
x

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])>